<a href="https://colab.research.google.com/github/mosesdaudu001/mvnwebapp/blob/master/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#00.Pytorch fundaments#


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as pit
print(torch.__version__)

1.12.1+cu113


## Introduction to tensors

### Creating tensors

### pytorch tensors are created using torch.tensor()

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim


0

In [5]:
# Get tensor back as python int

scalar.item()

7

In [6]:
#vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape


torch.Size([2, 2])

In [15]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape


torch.Size([1, 3, 3])

### Random Tensors

why random tensors?

random tensors are important because the way maunyt neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to bettter represent the data.

start with random data -> look at the data -> update random numbers -> look at data -> update random numbers


In [20]:
# create a random tensor of shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1840, 0.1953, 0.4549, 0.0419],
        [0.2512, 0.9753, 0.8472, 0.7642],
        [0.9872, 0.3272, 0.4891, 0.4802]])

In [21]:
# create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels (R G B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
moses_random_tensor = torch.rand(7,5)
moses_random_tensor

tensor([[0.9992, 0.9761, 0.4707, 0.4552, 0.4618],
        [0.8719, 0.7885, 0.0334, 0.7456, 0.7510],
        [0.7392, 0.6741, 0.3769, 0.1898, 0.4348],
        [0.0571, 0.0520, 0.1377, 0.4274, 0.0862],
        [0.9949, 0.3521, 0.1299, 0.3112, 0.9727],
        [0.7714, 0.0817, 0.2540, 0.3805, 0.1286],
        [0.4848, 0.5309, 0.4087, 0.7632, 0.4965]])

### zeros and ones tensors


In [23]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
## Create a tensor of all ones

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### creating a range of tensors and tensors-like

In [36]:
# use torch.range() not good instaed use torch.arrange()
one_to_ten=torch.arange(start=0,end=10,step=0.5)
one_to_ten

tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])

In [37]:
### creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0, 6.0 ,9.0], dtype=None, #what Datatype is the tensor (e.g 64bit or 32 bit)
                             device=None, # What device is your tensor on
                             requires_grad=False) # Whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

### Tensor datatypes

Tensor datatypes is one of the 3 big errors you'll run into with pytorch & deep learning:
1. Tensors not right datatype - to get datatype, use  (tensor.dtype)
2. Tensors not right shape - to get shape, use (tensor.shape)
3. Tensors not on right device - to get device, use (tensor.device)




In [40]:
float_32_tensor.dtype

torch.float32

In [41]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [43]:
int_32_tensor=torch.tensor([3, 6, 9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [45]:
int_32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [57]:
# craete a tensor

some_tensor=torch.rand([3,4], dtype=torch.float16)
some_tensor

tensor([[0.7295, 0.0288, 0.3130, 0.4238],
        [0.9883, 0.6567, 0.7485, 0.5508],
        [0.8501, 0.9761, 0.9790, 0.6582]], dtype=torch.float16)

In [58]:
# find some details about the tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")


tensor([[0.7295, 0.0288, 0.3130, 0.4238],
        [0.9883, 0.6567, 0.7485, 0.5508],
        [0.8501, 0.9761, 0.9790, 0.6582]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtractoin
* Multiplication (element-wise)
* Division
* Matrix multiplication